import type { Database } from "./types";

/**
 * Demonstration data. Replace with real project records at any time from
 * Settings → System → Reset / or by editing records in the application.
 */
export function seedDatabase(): Database {
  const p1 = "prj-nbe-akaki";
  const p2 = "prj-adama-road";
  const p3 = "prj-hawassa-wtp";

  return {
    settings: { theme: "light" },
    users: [
      {
        id: "usr-admin",
        username: "admin",
        password: "ascend2026",
        name: "System Administrator",
        role: "Administrator",
        active: true,
      },
      {
        id: "usr-ca",
        username: "contracts",
        password: "contracts",
        name: "Bedemariam Daniel",
        role: "Contract Administrator",
        active: true,
      },
      {
        id: "usr-claims",
        username: "claims",
        password: "claims",
        name: "Claims Engineer",
        role: "Claims Engineer",
        active: true,
      },
      {
        id: "usr-view",
        username: "viewer",
        password: "viewer",
        name: "Read-only User",
        role: "Viewer",
        active: true,
      },
    ],
    projects: [
      {
        id: p1,
        name: "NBE Akaki Campus — Main Works",
        contractRef: "NBE/CW/2023/01",
        employer: "National Bank of Ethiopia",
        consultant: "Ascend Consulting Engineers PLC",
        contractor: "Sunshine Construction PLC",
        contractType: "FIDIC Red Book",
        currencies: [
          { code: "USD", pct: 60 },
          { code: "ETB", pct: 40 },
        ],
        status: "in_progress",
        standing: "EOT Under Review",
        noticePeriodDays: 28,
        prelimRatePerDay: 18500,
        criticalFloatThreshold: 0,
        dates: {
          commencement: "2023-04-01",
          originalCompletion: "2025-10-31",
          revisedCompletion: "2026-04-30",
          eotGranted: "2026-02-14",
          contractExpiry: "2026-10-31",
        },
        createdAt: "2023-04-01T00:00:00.000Z",
      },
      {
        id: p2,
        name: "Adama — Awash Road Upgrading Lot 2",
        contractRef: "ERA/ADM-AWS/L2/2022",
        employer: "Ethiopian Roads Administration",
        consultant: "Ascend Consulting Engineers PLC",
        contractor: "Yotek Construction PLC",
        contractType: "PPA",
        currencies: [{ code: "ETB", pct: 100 }],
        status: "in_progress",
        standing: "Claim Under Evaluation",
        noticePeriodDays: 21,
        prelimRatePerDay: 220000,
        criticalFloatThreshold: 0,
        dates: {
          commencement: "2022-09-15",
          originalCompletion: "2025-09-14",
          revisedCompletion: "2026-03-31",
        },
        createdAt: "2022-09-15T00:00:00.000Z",
      },
      {
        id: p3,
        name: "Hawassa Water Treatment Plant",
        contractRef: "HWSSA/WTP/2019/07",
        employer: "Hawassa Water Supply & Sewerage Authority",
        consultant: "Ascend Consulting Engineers PLC",
        contractor: "Afro-Tsion Construction PLC",
        contractType: "FIDIC Yellow Book",
        currencies: [
          { code: "EUR", pct: 70 },
          { code: "ETB", pct: 30 },
        ],
        status: "completed",
        standing: "Final Account",
        noticePeriodDays: 28,
        prelimRatePerDay: 9000,
        criticalFloatThreshold: 0,
        dates: {
          commencement: "2019-06-01",
          originalCompletion: "2022-05-31",
          revisedCompletion: "2023-02-28",
          takingOver: "2023-03-10",
          defectsNotificationEnd: "2024-03-10",
        },
        createdAt: "2019-06-01T00:00:00.000Z",
      },
    ],
    claims: [
      {
        id: "clm-1",
        projectId: p1,
        ref: "EOT-CL-02",
        title: "EOT No. 02 — Late issue of structural drawings",
        type: "Extension of Time",
        status: "Under Review",
        submittedDate: "2026-05-12",
        claimedDays: 120,
        approvedDays: 75,
        currency: "USD",
        claimedAmount: 2000000,
        approvedAmount: 1500000,
        settledAmount: null,
        notes: "Engineer's partial determination received; substantiation resubmitted.",
      },
      {
        id: "clm-2",
        projectId: p1,
        ref: "PC-CL-01",
        title: "Prolongation cost associated with EOT No. 01",
        type: "Prolongation Cost",
        status: "Settled",
        submittedDate: "2025-11-03",
        claimedDays: null,
        approvedDays: null,
        currency: "USD",
        claimedAmount: 450000,
        approvedAmount: 380000,
        settledAmount: 380000,
      },
      {
        id: "clm-3",
        projectId: p2,
        ref: "ERA/CL-05",
        title: "Right-of-way handover delay — Km 14+000 to Km 21+500",
        type: "Employer Risk",
        status: "Submitted",
        submittedDate: "2026-07-21",
        claimedDays: 168,
        approvedDays: null,
        currency: "ETB",
        claimedAmount: 45000000,
        approvedAmount: null,
        settledAmount: null,
      },
      {
        id: "clm-4",
        projectId: p3,
        ref: "HWSSA/CL-09",
        title: "Price escalation on imported mechanical equipment",
        type: "Price Escalation",
        status: "Settled",
        submittedDate: "2022-10-04",
        claimedDays: null,
        approvedDays: null,
        currency: "EUR",
        claimedAmount: 640000,
        approvedAmount: 520000,
        settledAmount: 520000,
      },
    ],
    events: [
      {
        id: "evt-1",
        projectId: p1,
        ref: "DE-001",
        title: "Late issue of revised structural drawings",
        category: "Employer / Engineer information",
        activityCode: "STR-1200",
        activityName: "Superstructure — Block B",
        startDate: "2025-02-10",
        endDate: "2025-06-08",
        risk: "employer",
        excusable: true,
        compensable: "yes",
        floatBeforeDays: 0,
        criticalAtEvent: true,
        completionImpactDays: 118,
        claimedDays: 120,
        grantedDays: 75,
        status: "partial",
        noticeGivenDate: "2025-03-01",
        noticePeriodDays: 28,
        ratePerDay: 18500,
        claimId: "clm-1",
      },
      {
        id: "evt-2",
        projectId: p1,
        ref: "DE-002",
        title: "Contractor shortage of formwork carpenters",
        category: "Contractor resource",
        activityCode: "STR-1240",
        activityName: "Slab casting — Block B L4",
        startDate: "2025-03-18",
        endDate: "2025-05-02",
        risk: "contractor",
        excusable: false,
        compensable: "no",
        floatBeforeDays: 0,
        criticalAtEvent: true,
        completionImpactDays: 45,
        claimedDays: 0,
        grantedDays: 0,
        status: "draft",
        noticePeriodDays: 28,
      },
      {
        id: "evt-3",
        projectId: p2,
        ref: "DE-014",
        title: "Delayed right-of-way handover Km 14+000 – Km 21+500",
        category: "Employer risk / site access",
        activityCode: "ERT-2200",
        activityName: "Earthworks Section 3",
        startDate: "2025-01-05",
        endDate: "2025-06-22",
        risk: "employer",
        excusable: true,
        compensable: "yes",
        floatBeforeDays: 12,
        criticalAtEvent: true,
        completionImpactDays: 156,
        claimedDays: 168,
        grantedDays: null,
        status: "submitted",
        noticeGivenDate: "2025-01-20",
        noticePeriodDays: 21,
        ratePerDay: 220000,
        claimId: "clm-3",
      },
    ],
    letters: [
      {
        id: "ltr-1",
        projectId: p1,
        ref: "ACE/NBE/OUT/3118/26",
        date: "2026-05-12",
        subject: "Submission of EOT Claim No. 02 with delay analysis",
        sender: "Ascend Consulting Engineers PLC",
        recipient: "National Bank of Ethiopia",
        type: "EOT",
        description:
          "Formal submission of EOT No. 02 (120 days) with time impact analysis and supporting records.",
        claimId: "clm-1",
        eventId: "evt-1",
        attachments: [],
      },
      {
        id: "ltr-2",
        projectId: p1,
        ref: "NBE/ACE/IN/0442/26",
        date: "2026-06-28",
        subject: "Engineer's determination — EOT Claim No. 02",
        sender: "National Bank of Ethiopia",
        recipient: "Ascend Consulting Engineers PLC",
        type: "Response",
        description: "Partial determination granting 75 days; substantiation requested for the balance.",
        claimId: "clm-1",
        attachments: [],
      },
      {
        id: "ltr-3",
        projectId: p2,
        ref: "ACE/ERA/OUT/0781/25",
        date: "2025-01-20",
        subject: "Notice of delay — right-of-way handover Section 3",
        sender: "Ascend Consulting Engineers PLC",
        recipient: "Ethiopian Roads Administration",
        type: "Notice",
        description: "Contractual notice issued within 21 days of the delaying event.",
        eventId: "evt-3",
        attachments: [],
      },
    ],
    actions: [
      {
        id: "act-1",
        projectId: p1,
        actionType: "Submit EOT",
        weekStarting: "2026-09-14",
        dueDate: "2026-09-15",
        description: "Submit revised EOT substantiation to the Engineer.",
        linkedRef: "EOT-CL-02",
        status: "planned",
        priority: "must",
      },
      {
        id: "act-2",
        projectId: p2,
        actionType: "Send Letter",
        weekStarting: "2026-09-14",
        dueDate: "2026-09-17",
        description: "Issue reminder on outstanding right-of-way handover.",
        linkedRef: "ERA/CL-05",
        status: "planned",
        priority: "attention",
      },
      {
        id: "act-3",
        projectId: p1,
        actionType: "Other Action",
        weekStarting: "2026-09-14",
        dueDate: "2026-09-19",
        description: "Update letter registry and delay register with July–August correspondence.",
        status: "planned",
        priority: "normal",
      },
    ],
    documents: [
      {
        id: "doc-1",
        projectId: p1,
        contract: "FIDIC Red Book",
        name: "Contract Agreement",
        docType: "Contract",
        ref: "NBE/CW/2023/01",
        date: "2023-03-20",
      },
      {
        id: "doc-2",
        projectId: p1,
        contract: "FIDIC Red Book",
        name: "Particular Conditions of Contract",
        docType: "Contract",
        ref: "PCC",
        date: "2023-03-20",
      },
      {
        id: "doc-3",
        projectId: p3,
        contract: "FIDIC Yellow Book",
        name: "Taking-Over Certificate",
        docType: "Certificate",
        ref: "TOC-001",
        date: "2023-03-10",
      },
    ],
  };
}
